apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PV name
  name: nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    # Access Modes:
    # - ReadWriteMany (RW from multi nodes)
    # - ReadWriteOnce (RW from a node)
    # - ReadOnlyMany (R from multi nodes)
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

